services:
  db:
    image: postgres:14-alpine
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - auth-api_net

  nginx:
    image: nginx:1.21.6
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/configs:/etc/nginx/conf.d:ro
    depends_on:
      - auth-api
    ports:
      - 80:80
    networks:
      - auth-api_net

  auth-api:
    build: ./src
    image: authapi-image
    expose:
      - 5000
    env_file:
      - .env
    depends_on:
      - db
    restart: on-failure
    networks:
      - auth-api_net

  redis:
    restart: unless-stopped
    expose:
      - 6379
    image: redis:6.2.5
    volumes:
      - redis_data:/data
    networks:
      - auth-api_net

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "5775:5775/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14268:14268"
      - "9411:9411"
    networks:
      - auth-api_net

networks:
    auth-api_net:
        name: auth-api_net
        driver: bridge

volumes:
  postgres_data:
    name: postgres_data_users
  es_data:
    name: es_data
    external: true
  redis_data:
    name: redis_data
    external: true